default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.19.0
    hooks:
      - id: typos
        args: []
        stages: [pre-commit]
      - id: typos
        name: commit-msg-typos
        stages: [commit-msg]
